Self install and self uninstall. Added INSTALL file, added install instructions to README

diff --git a/bin/s b/bin/s
--- a/bin/s
+++ b/bin/s
@@ -52,6 +52,75 @@ if [ -f $CONFIGFILE ]; then
   source $CONFIGFILE
 fi
 
+function remove {
+  if [ -f "/usr/local/bin/s" ]; then
+    sudo rm -f "/usr/local/bin/s"
+    echo "Removed s from /usr/local/bin/"
+  fi
+  if [ -f "/usr/bin/s" ]; then
+    sudo rm -f "/usr/bin/s"
+    echo "Removed s from /usr/bin/"
+  fi
+  if [ -f "/bin/s" ]; then
+    sudo rm -f "/bin/s"
+    echo "Removed s from /bin/"
+  fi
+  if [ -f $HOME/bin/s ]; then
+    sudo rm -f $HOME/bin/s
+    echo "Removed s from $HOME/bin/"
+  fi
+  exit 0  
+}
+ 
+function install {
+  if [[ "$OPT_INSTALL" != "" ]]; then  
+    case "$OPT_INSTALL" in
+        home) 
+          if [ ! -d $HOME/bin ]; then
+            mkdir $HOME/bin
+            chmod 700 $HOME/bin
+          fi
+          cp -f s $HOME/bin/s
+          chmod 700 $HOME/bin/s
+          echo "Installed s to ~/bin/ -- Make sure ~/bin is in your PATH"
+          exit 0
+          ;;
+        system) 
+          if [ -d "/usr/local/bin" ]; then
+            sudo cp -f s "/usr/local/bin/s"
+            sudo chown root "/usr/local/bin/s"
+            sudo chmod 755 "/usr/local/bin/s"
+            echo "Installed s to /usr/local/bin/"
+            exit 0
+          fi
+          if [ -d "/usr/bin" ]; then
+            sudo cp -f s "/usr/bin/s"
+            sudo chown root "/usr/bin/s"
+            sudo chmod 755 "/usr/bin/s"
+            echo "Installed s to /usr/bin/ (/usr/local/bin doesn't exist!)"
+            exit 0
+          fi
+          if [ -d "/bin" ]; then
+            sudo cp -f s "/bin/s"
+            sudo chown root "/bin/s"
+            sudo chmod 755 "/bin/s"
+            echo "Installed s to /usr/bin/ (/usr/local/bin and /usr/bin/ don't exist!)"
+            exit 0
+          fi
+          echo "Couldn't find a suitable bin directory on this system. Maybe try 's --install home'?"
+          exit 1
+          ;;
+        *) 
+          echo "Install must be either 'home' or 'system'."
+          exit 1;;
+    esac
+  fi
+  echo "Install where?"
+  echo " Install for this user only:  's --install home'"               
+  echo " Install for all users (requires root):  's --install system'"
+  exit 1
+}
+
 function do_connect() {
     list=(`ls -A $CONFIGDIR | sort`)
     for filename in "${list[@]}"
@@ -130,6 +199,26 @@ do
                 OPT_SAVE=${OPTARG#*=}
                 opt=${OPTARG%=$val}
                 ;;
+            remove)
+                OPT_INSTALL="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
+                if [[ $OPT_INSTALL == "force" ]]; then
+                  remove
+                  exit 0
+                fi
+                echo "Do you really want to remove s from all likely places? 's --remove force'"
+                exit 1
+                ;;
+            help) 
+                show_help
+                ;;    
+            install)
+                OPT_INSTALL="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
+                install
+                ;;
+            install=*)
+                OPT_INSTALL=${OPTARG#*=}
+                install
+                ;;
             *)
                 if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
                     echo "s: Unknown option --${OPTARG}" >&2
@@ -151,6 +240,7 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
+#The original dash-less command args. Don't add to these anymore.
 case "$1" in
    help) show_help;;
    show) show_config;;
@@ -176,16 +266,12 @@ if [[ "$1" == *@* ]]; then
     # what should this behavior be? "save(y/n), name:?"
     # right now, warn and die, assuming user will want to up arrow and add a name to the last command line
     if [[ "$OPT_SAVE" != "" ]]; then
-      
       save_config
       exit 0
     fi
     echo "s: No configuration name given as argument to --save or as last comand line parameter."
     exit 1
 fi
-
-
-
 
 # do_connect is safe to call, will error and die pretty if the congiguration doesn't exist.
 do_connect $1
